[package]
name = "zkitaptopdf"
version = "0.1.0"
edition = "2024"
include = ["src/**", "bin/**"]

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
blowfish = "0.9.1"
byteorder = "1.5.0"
cipher = "0.4.4"
image = "0.25.9"
notify = "8.2.0"
swf = "0.2.2"
