blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/vrdons/zKitap2Pdf/security/advisories/new
    about: Report security vulnerabilities privately
  - name: Discussions
    url: https://github.com/vrdons/zKitap2Pdf/discussions
    about: Ask questions and discuss ideas
